[package]
name = "engine"
version = "0.1.0"
license = "ISC"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
diffy = "0.2.1"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
